name: Linux AArch64 Glibc CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: aarch64
        distro: archarm_latest
      run: |
        sudo pacman -Syuu --noconfirm
        sudo pacman -S --noconfirm jsoncpp clang websocketpp glfw-wayland curl
        sudo pacman -S --noconfirm --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
        wget https://github.com/ocornut/imgui/archive/refs/tags/v1.88.tar.gz
        tar xf v1.88.tar.gz
        mv imgui-1.88 imgui
        yay -S crow
        make

    - name: Archive gui binary
      uses: actions/upload-artifact@v3
      with:
        name: kryptobot_gui
        path: main.out
          
    - name: Archive headless binary
      uses: actions/upload-artifact@v3
      with:
        name: kryptobot_headless
        path: headless.out
