name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update
          wget https://github.com/ocornut/imgui/archive/refs/tags/v1.88.tar.gz
          tar xf v1.88.tar.gz
          mv imgui-1.88 imgui
          sudo apt-get install libjsoncpp-dev clang libcurl-dev libwebsocketpp-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
