name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install tools
      run: |
        sudo apt-get update
        wget https://github.com/ocornut/imgui/archive/refs/tags/v1.88.tar.gz
        tar xf v1.88.tar.gz
        mv imgui-1.88 imgui
        wget https://github.com/CrowCpp/Crow/releases/download/v1.0%2B5/crow-v1.0+5.deb
        sudo apt install -y ./crow-v1.0+5.deb
        sudo apt install -y libjsoncpp-dev clang libwebsocketpp-dev libglfw3-dev libimgui-dev
    - name: make
      run: make
